from typing import List, Optional
from tvara.prompts.generic_prompts import base_prompt
from tvara.models.model_factory import ModelFactory
class Agent:
    """
    Initializes a new Agent instance.
    Args:
        name (str): The name of the agent.
        model (str): The model used by the agent.
        description (Optional[str]): A brief description of the agent.
        tools (Optional[List[str]]): A list of tools available to the agent.
        connectors (Optional[List[str]]): A list of connectors used by the agent.
        model (str): The model used by the agent.
        custom_prompt (Optional[str]): A custom prompt for the agent.
        api_key (Optional[str]): The API key for the agent, if applicable.
    """
    def __init__(self, name: str, model: str, description: str = None, tools: Optional[List[str]] = None, connectors: Optional[List[str]] = None, custom_prompt: Optional[str] = None, api_key: Optional[str] = None):
        self.name = name
        self.model = model
        self.tools = tools if tools is not None else []
        self.connectors = connectors if connectors is not None else []
        self.description = description
        self.custom_prompt = custom_prompt
        self.api_key = api_key

    def get_system_prompt(self) -> str:
        """
        Generates the system prompt for the agent.
        Returns:
            str: The system prompt for the agent.
        """
        return base_prompt(self.description, self.tools) if self.description else self.custom_prompt

    def run(self, input_data: str) -> str:
        """
        Runs the agent with the provided input data.
        Args:
            input_data (str): The input data for the agent to process.
        Returns:
            str: The output generated by the agent.
        """
        default_system_prompt = base_prompt(self.description, self.tools) if self.description else self.custom_prompt
        model_instance = ModelFactory.create_model(self.model, self.api_key)
        return model_instance.get_response(input_data, default_system_prompt)